version: '3.8'

services:
  searxng:
    image: searxng/searxng:latest
    container_name: celflow-searxng
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://localhost:8080/
      - INSTANCE_NAME=CelFlow-SearXNG
    volumes:
      - ./searxng/searxng:/etc/searxng:ro
    restart: unless-stopped
